import { DEFAULT_FONT_SIZE, DEFAULT_LINE_HEIGHT } from "./constants";

export default (selector) => `
${selector}, ${selector} * {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: ${DEFAULT_FONT_SIZE}px;
    line-height: ${DEFAULT_LINE_HEIGHT}px;
    font-family: Courier New;
	vertical-align: baseline;
    position: absolute;
    display: inline-block;

    background-attachment:scroll;
    background-color:transparent;
    background-image:none; /* This rule affects the use of pngfix JavaScript http://dillerdesign.com/experiment/DD_BelatedPNG for IE6, which is used to force the browser to recognise alpha-transparent PNGs files that replace the IE6 lack of PNG transparency. (The rule overrides the VML image that is used to replace the given CSS background-image). If you don't know what that means, then you probably haven't used the pngfix script, and this comment may be ignored :) */
    background-position:0 0;
    background-repeat:repeat;
    border-color:black;
    border-color:currentColor; /* 'border-color' should match font color. Modern browsers (incl. IE9) allow the use of "currentColor" to match the current font 'color' value <http://www.w3.org/TR/css3-color/#currentcolor>. For older browsers, a default of 'black' is given before this rule. Guideline to support older browsers: if you haven't already declared a border-color for an element, be sure to do so, e.g. when you first declare the border-width. */
    border-radius:0;
    border-style:none;
    border-width:medium;
    bottom:auto;
    clear:none;
    clip:auto;
    color:inherit;
    counter-increment:none;
    counter-reset:none;
    cursor:auto;
    float:none;
    font-variant:normal;
    height:auto;
    left:auto;
    letter-spacing:normal;
    list-style-position: outside;
    list-style-image: none;
    max-height:none;
    max-width:none;
    min-height:0;
    min-width:0;
    opacity:1;
    outline:none;
    quotes: "" "";
    right:auto;
    table-layout:auto;
    text-indent:0;
    text-transform:none;
    top:auto;
    unicode-bidi:normal;
    visibility:inherit;
    white-space:normal;
    width:auto;
    word-spacing:normal;
    z-index:auto;

    -webkit-background-origin: padding-box;
    background-origin: padding-box;
-webkit-background-clip: border-box;
    background-clip: border-box;
-webkit-background-size: auto;
-moz-background-size: auto;
    background-size: auto;
-webkit-border-image: none;
-moz-border-image: none;
 -o-border-image: none;
    border-image: none;
-webkit-border-radius:0;
-moz-border-radius:0;
    border-radius: 0;
-webkit-box-shadow: none;
    box-shadow: none;
-webkit-box-sizing: content-box;
-moz-box-sizing: content-box;
    box-sizing: content-box;
-webkit-column-count: auto;
-moz-column-count: auto;
    column-count: auto;
-webkit-column-gap: normal;
-moz-column-gap: normal;
    column-gap: normal;
-webkit-column-rule: medium none black;
-moz-column-rule: medium none black;
    column-rule: medium none black;
-webkit-column-span: 1;
-moz-column-span: 1; /* doesn't exist yet but probably will */
    column-span: 1;
-webkit-column-width: auto;
-moz-column-width: auto;
    column-width: auto;
font-feature-settings: normal;
overflow-x: visible;
overflow-y: visible;
-webkit-hyphens: manual;
-moz-hyphens: manual;
    hyphens: manual;
-webkit-perspective: none;
-moz-perspective: none;
-ms-perspective: none;
 -o-perspective: none;
    perspective: none;
-webkit-perspective-origin: 50% 50%;
-moz-perspective-origin: 50% 50%;
-ms-perspective-origin: 50% 50%;
 -o-perspective-origin: 50% 50%;
    perspective-origin: 50% 50%;
-webkit-backface-visibility: visible;
-moz-backface-visibility: visible;
-ms-backface-visibility: visible;
 -o-backface-visibility: visible;
    backface-visibility: visible;
text-shadow: none;
-webkit-transition: all 0s ease 0s;
    transition: all 0s ease 0s;
-webkit-transform: none;
-moz-transform: none;
-ms-transform: none;
 -o-transform: none;
    transform: none;
-webkit-transform-origin: 50% 50%;
-moz-transform-origin: 50% 50%;
-ms-transform-origin: 50% 50%;
 -o-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
-webkit-transform-style: flat;
-moz-transform-style: flat;
-ms-transform-style: flat;
 -o-transform-style: flat;
    transform-style: flat;
word-break: normal;

    direction:ltr;
    text-align: left; /* for IE, Opera */
    text-align: start; /* recommended W3C Spec */
    color: black;
    font-style:normal;
    font-weight:normal;
    text-decoration:none;
    list-style-type:disc;

    contain: size layout style;
    }
`;
